version: '3.7'

services:
  # MongoDB
  cadmus-chgc-mongo:
    image: mongo
    container_name: cadmus-chgc-mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod --logpath=/dev/null # --quiet
    ports:
      - 27017:27017
    networks:
      - cadmus-chgc-network

  # PostgreSQL
  cadmus-chgc-pgsql:
    image: postgres
    container_name: cadmus-chgc-pgsql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - cadmus-chgc-network

  # Cadmus CHGC API
  cadmus-chgc-api:
    image: vedph2020/cadmus-chgc-api:3.0.9
    container_name: cadmus-chgc-api
    ports:
      - 5078:80
    depends_on:
      - cadmus-chgc-mongo
      - cadmus-chgc-pgsql
    environment:
      - CONNECTIONSTRINGS__DEFAULT=mongodb://cadmus-chgc-mongo:27017/{0}
      - CONNECTIONSTRINGS__INDEX=Server=cadmus-chgc-pgsql;port=5432;Database={0};User Id=postgres;Password=postgres;Include Error Detail=True
      - SEED__INDEXDELAY=25
      - MESSAGING__APIROOTURL=http://cadmusapi.azurewebsites.net
      - MESSAGING__APPROOTURL=http://cadmusapi.com/
      - MESSAGING__SUPPORTEMAIL=support@cadmus.com
      - SERILOG__CONNECTIONSTRING=mongodb://cadmus-chgc-mongo:27017/cadmus-logs
      - STOCKUSERS__0__PASSWORD=P4ss-W0rd!
    networks:
      - cadmus-chgc-network

networks:
  cadmus-chgc-network:
    driver: bridge
